name: ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      [ main ]
  workflow_dispatch:

jobs:
  # Check XC32 compilation
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download Microchip XC32 Compiler
        run: wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/xc32-v4.30-full-install-linux-x64-installer.tar
      - name: Extract & Install Microchip XC32 Compiler
        run: tar -xf xc32-v4.30-full-install-linux-x64-installer.tar
      - run: chmod a+x xc32-v4.30-full-install-linux-x64-installer.run
      - run: sudo ./xc32-v4.30-full-install-linux-x64-installer.run --mode unattended --debuglevel 4 --netservername localhost --LicenseType FreeMode # --installdir /Applications/microchip/xc32/v4.30/bin/
      - run: ls -al /opt/microchip/xc32/v4.30/bin
      - name: Replace Makefile-local-default.mk by CI related
        run: mv ./config/Makefile-ci-default.mk ./firmware/open-risk-logger-samd21-xpro-proto.X/nbproject/Makefile-local-default.mk
      - name: Compile project Makefile
        run: cd ./firmware/open-risk-logger-samd21-xpro-proto.X && make